clims1 = [0 4];
clims2 = [0 0.7];
clims3 = [0 7];
clims4 = [0 1];
clims5 = [0 4];
clims6 = [0 3];
clims7 = [0 1];
figure('color',[1 1 1]);
ima = tight_subplot(2,7,[0.1 0.01],[0 0.1],0);
axes(ima(1));imagesc(ima_pn(:,:,1),clims1);colormap gray;axis off;title('O Ka');
axes(ima(2));imagesc(ima_pn(:,:,2),clims2);colormap gray;axis off;title('Ca Ka');
axes(ima(3));imagesc(ima_pn(:,:,3),clims3);colormap gray;axis off;title('Ti Ka');
axes(ima(4));imagesc(ima_pn(:,:,4),clims4);colormap gray;axis off;title('Ti Kb');
axes(ima(5));imagesc(ima_pn(:,:,5),clims5);colormap gray;axis off;title('Nd La');
axes(ima(6));imagesc(ima_pn(:,:,6),clims6);colormap gray;axis off;title('Nd Lb');
axes(ima(7));imagesc(ima_pn(:,:,7),clims7);colormap gray;axis off;title('Nd Lb4');
axes(ima(8));imagesc(ima_fil(:,:,1),clims1);colormap gray;axis off;colorbar;
axes(ima(9));imagesc(ima_fil(:,:,2),clims2);colormap gray;axis off;colorbar;
axes(ima(10));imagesc(ima_fil(:,:,3),clims3);colormap gray;axis off;colorbar;
axes(ima(11));imagesc(ima_fil(:,:,4),clims4);colormap gray;axis off;colorbar;
axes(ima(12));imagesc(ima_fil(:,:,5),clims5);colormap gray;axis off;colorbar;
axes(ima(13));imagesc(ima_fil(:,:,6),clims6);colormap gray;axis off;colorbar;
axes(ima(14));imagesc(ima_fil(:,:,7),clims7);colormap gray;axis off;colorbar;